name: workflow1

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: display current date and time 
        run: date
  job2:
    name: second_job
    runs-on: windows-latest
    steps:
      - name: display current date and time
        run: Get-Date
  job3:
    name: third_job
    runs-on: macos-latest
    steps:
      - name: display current date and time
        run: date
  job4:
    name: fourth_job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: display current date and time
        run: date