name: workflow2

on: 
  workflow_dispatch:
    

jobs:
  job1:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Show directory structure
        run: ls      
  job2:
    name: second_job
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0